(define (register_customer username email password full_name . rest))
(define (login_customer username password))
(define (get_customer customer_id))
(define (update_customer_profile customer_id new_email new_phone new_address))
(define (reset_password email new_password))
(define (verify_email token))
(define (add_payment_method customer_id type card_number expiry_month expiry_year cvv holder_name . rest))
(define (list_payment_methods customer_id))
(define (delete_payment_method pm_id))
(define (process_payment customer_id payment_method_id amount . rest))
(define (list_payments customer_id))
(define (get_payment_details payment_id))
(define (create_refund payment_id amount . rest))
(define (process_refund refund_id))
(define (simulate_chargeback payment_id amount . rest))
(define (resolve_chargeback chargeback_id . rest))
(define (create_fraud_review payment_id customer_id . rest))
(define (decide_fraud_review review_id decision reviewer_email reviewer_password))
(define (admin_list_all_customers))
(define (admin_export_all_data))
(define (search_payments search_term))
(define (process_recurring_billing))
(define (handle_webhook payload))
(define (ban_customer customer_id))
(define (generate_api_key customer_id))
